### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by oaustegard**
Added a much simpler bookmarklet approach to reduce friction

### CODE REVIEW

**Comment by oaustegard** [comment]
Process... https://austegard.com/pv?16bfb16dad0de04440c695b3f1f67521

**Comment by hamelsmu** [comment]
Wow this looks cool.  Sorry for not seeing it before!

**Comment by hamelsmu** [comment]
I will test this when back at my computer 

I didn't even know what a bookmarklet is !!!! But wow 🤯

**Comment by oaustegard** [comment]
What you don't work all Saturday? 😉

**Comment by hamelsmu** [comment]
I'm trying to figure out how to trigger the alert when the we are on a raw github gist (which I know people are going to click on by accident) but I can't seem to make that work.  

I get console errors in that case.  I made some minor changes to this PR though in the meantime.

**Comment by hamelsmu** [comment]
I think the bookmarklet is blocked on raw content, for example this is what I get when I try to do this on `https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks/01.07-Timing-and-Profiling.ipynb`

```
Blocked script execution in 'https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks/01.07-Timing-and-Profiling.ipynb' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

I am still a noob so learning about this.

**Comment by hamelsmu** [comment]
ok I'm reading up on that and I guess they block the javascript from running on raw pages because they sandbox it.

**Comment by oaustegard** [comment]
Thanks for incorporating it!

**Pull request merged**
